### ISSUE TITLE
Suggestion: Lib grouping / Plugin detection

### ISSUE THREAD

**Issue by Swader** [julianshapiro/libscore#4]
Currently, a big part of the lib list is jQuery plugins. It would be swell if users could group all the `$` "libs" into one, or if libscore did this automatically with an added "plugin" filter, so that the parent project was the only thing visible (jQuery), thus being more comparable to other actual libraries.

**Comment by jerone** [comment]
:+1: [Top libs list](http://libscore.com/#*) is a bit unreadable with all those jQuery plugins. Grouping sounds great.

**Comment by julianshapiro** [comment]
I think the jQuery plugins work at standalone entries. Yes, they are for jQuery, but they are otherwise completely standalone and very popular projects :)
