### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by miketaylr** [julianshapiro/libscore#6]
Hi! This project looks super interesting. I would like to collaborate and/or extend what you're doing. Where can I find the source code?

**Comment by jerone** [comment]
:shipit: Bumping & subscribing

**Comment by miketaylr** [comment]
![](https://cldup.com/WuRNX4cEDd.thumb.png)

**Comment by julianshapiro** [comment]
Hahaha! Hang tight :) cc @thomasdavis: When are you releasing the next data dump?

**Comment by miketaylr** [comment]
:P just being silly. And still looking forward to forking your project. ^_^

**Comment by PeterDaveHello** [comment]
any updates? what about the source of the website?

**Comment by julianshapiro** [comment]
This will officially be open sourced soon — we're releasing a chrome extension that'll help people contribute data, and that extension will include the full source.

**Comment by PeterDaveHello** [comment]
Does this project still going to be open source :smile:

**Comment by digitarald** [comment]
Adding my :+1: to show my excitement that this project got a grant by Stripe to be an open-source project!

**Comment by paulirish** [comment]
@jhchen @jesseDO can you guys help here? please?

**Comment by jesseDO** [comment]
@paulirish I will check in with @julianshapiro on this one, hang tight.

**Comment by julianshapiro** [comment]
I was hesitant for a long time for some arguably good reasons. Some things have happened (positive things!) that now compel me to finally open source this. My vote is *yes*. Thoughts @jhchen and @jesseDO ?

**Comment by jesseDO** [comment]
:+1: I am absolutely for releasing the codebase. Let's make this happen.

**Comment by miketaylr** [comment]
:tada: :balloon:

**Comment by jhchen** [comment]
I vote yes as well. Sounds like it's unanimous.

**Comment by vladikoff** [comment]
Woo this is exciting!

**Comment by jesseDO** [comment]
Officially Launched:  https://medium.com/@jhchen/open-sourcing-libscore-the-javascript-tracker-b41eff3b8e36#.6la4x29dv cc @paulirish

**Comment by miketaylr** [comment]
https://github.com/libscore for those wanting to skip medium.

**Comment by paulirish** [comment]
awesome; thanks for this. 

great work @jesseDO and @jhchen
