### ISSUE TITLE
Distinguishing between libraries or objects that have the same name

### ISSUE THREAD

**Issue by jslegers** [julianshapiro/libscore#8]
I was trying to use your app to find out who's using the JS components of [Cascade Framework](http://www.cascade-framework.com/). Unfortunately, the results were useless :

* Cascade Framework uses an object named `App`, which takes up the role of a [front controller](http://en.wikipedia.org/wiki/Front_Controller_pattern) and is used mostly for centralized asynchronous JS loading (including polyfills for older browsers). As this is a pretty common name, [the results](http://libscore.com/#App) were useless.
* Cascade Framework uses an object named `Detector`, which is really just a merger of `Modernizr` and `jQuery.browser`. It is used mostly to detect which polyfills to load, to add helper classes to the HTML and to dynamically load either jQuery 1 or jQuery 2. As this is also a pretty common name, [the results](http://libscore.com/#Detector) were useless as well.
* Cascade Framework uses an object named `$.fn.cascade`. This object adds some JS behaviors to the DOM for eg. user interaction. I would have thought that this object was specific enough to Cascade Framework to only get correct results, but again [the results](http://libscore.com/#$.fn.cascade) were useless. For example, some of the results involved a WooCommerce plugin for Wordpress named [Cascade Filter Importer](http://wcf4fdemo.smadit.com/).

While the current implementation may be useful to track use of libraries as popular as `jQuery`, `Underscore`, `LoDash` or `Angular` or libraries with very exotic names, I'd expect this issue to apply to most other libraries. 

I believe `libscore` has a lot of potential, but only if this issue is solved. If not, the accuracy of the results will be too unreliable for most use cases for `libscore` to be useful.

#### Some suggestions on how to fix this issue :

* Detect the presence of a `version` property, and `authors` property or any other property that provides meta-information about a library and compare its value with other occurrences of an object

* Compare the number of properties between libraries

*  Test whether two libraries have the same first X properties.

* Compare the filesize of libraries 

* Compare the Constructors or Prototypes of objects

**Comment by julianshapiro** [comment]
Yup, good idea. Problem is that archiving and searching this requires quite a bit of server overhead. For the time being, if I see duplicates that are each sufficiently popular to warrant a distinction on Libscore, I'm happy to do it manually. I'll be doing this for underscore/lo-dash.

Thanks so much for this. Sorry about the slow response :)
